[theme]
base = "dark"
primaryColor = "#d0d0d0"
backgroundColor = "#0c0c0c"
secondaryBackgroundColor = "#191919"
textColor = "#eeeeee"
font = "sans serif"
linkColor = "#cccccc"
borderColor = "#333333"
dataframeBorderColor = "#333333"
dataframeHeaderBackgroundColor = "#202020"
chartCategoricalColors = ["#eeeeee", "#aaaaaa", "#777777", "#555555"]
chartSequentialColors = ["#222222", "#555555", "#999999", "#eeeeee"]
redColor = "#b8b8b8"
orangeColor = "#b8b8b8"
yellowColor = "#b8b8b8"
blueColor = "#b8b8b8"
greenColor = "#b8b8b8"
violetColor = "#b8b8b8"
grayColor = "#b8b8b8"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 5
headless = true
